#!/usr/bin/env bash

# 
# GET /api/content/v1/parser?url=http://blog.readability.com/2011/02/step-up-be-heard-readability-ideas/&token=1b830931777ac7c2ac954e9f0d67df437175e66e
# 
# 
# jason-api-app-name
# 
# Parser API Token:
# 07d2a53679fea63b7ef1a01a2e1612cd63f3b4fa
# 
# 
# Reader API:
# key: jason-api-app-name
# secret: 3RkvN6uj2PBwpZkPAmUYnBPYgu7Gs2L5
#
#
# OAuth: API Keys + User Authorization via Callbacks—Recommended for Web Apps
#
# OAuth Endpoints:
# https://www.readability.com/api/rest/v1/oauth/authorize/
# https://www.readability.com/api/rest/v1/oauth/request_token/
# https://www.readability.com/api/rest/v1/oauth/access_token/
#
# XAuth: API Keys + Username & Password—Recommended for Native Apps
#
# XAuth requires a single endpoint for authorization:
# https://www.readability.com/api/rest/v1/oauth/access_token/
#
export READABILITY_CONSUMER_KEY='jason-api-app-name'
export READABILITY_CONSUMER_SECRET='3RkvN6uj2PBwpZkPAmUYnBPYgu7Gs2L5'
export READABILITY_PARSER_TOKEN='07d2a53679fea63b7ef1a01a2e1612cd63f3b4fa'
export READABILITY_USERNAME='kumpfjn'
export READABILITY_PASSWORD='wj5np47dn'

